# Generated by Django 4.1 on 2022-10-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
